from distutils.core import setup
import py2exe

setup(
    name='Memory Lane',
    version='1.0',
    description='An app that uses GPS data and machine learning to create a digital map of your life\'s most important moments, making it easy to revisit them.',
    author='Poorna Sai Dumpa',
    author_email='purnasai1312@gmail.com',
    url='https://github.com/purnasara/MemoryLane.git',
    options={
        'py2exe': {
            'bundle_files': 1,  # Bundle all files into the executable
            'compressed': True,  # Compress the library archive
            'optimize': 2,  # Optimize generated bytecode
            'excludes': ['Tkinter'],  # Exclude libraries that are not needed
            'includes': ['numpy', 'scipy', 'sklearn'],  # Include additional libraries
        }
    },
    windows=[{'script': 'memory_lane.py'}],  # The name of your main script file
    zipfile=None  # Do not create a zipfile for the library archive
)
